### ISSUE TITLE
GBA pulse channel(s) louder than it should be?

### ISSUE THREAD

**Issue by bryc** [mgba-emu/mgba#1005]
In latest mGBA libretro, the pulse channels sound louder and overpowers the sampled (PCM) channels. I think I've played older versions of mGBA that didn't have this issue. _Going to edit this issue ASAP after testing the desktop versions and seeing if there's a difference between old versions/I'm not crazy_.

To show what I mean here is a zip with various 8sec excerpts of a song (gpSP, meteor, mGBA, beetle, vbanext). mgba.ogg is the black sheep in the bunch where the pulse channels are too loud : [firered.zip](https://github.com/mgba-emu/mgba/files/1776231/firered.zip)

You can hardly hear the cymbal crashes in the mGBA recording :disappointed:

**Comment by endrift** [comment]
Can you check to see if this happens in 0.6.1 too?

**Comment by bryc** [comment]
Doesn't happen in 0.6.1, 0.6.0, 0.5.2 or 0.5.1, or the latest dev build (2018-03-01-win32-5040-b02b9930). Basically none of the desktop builds are affected

**Comment by arkazal** [comment]
So... this is still happening to me. Using 0.6.0 and 0.6.1 and I'm getting the EXACT sound that bryc uploaded in his firered.zip file. I just tested the exact same game in mGBA, and on VBA-next, it doesn't sound like this.

I made an update to the issue I posted a while back today
https://github.com/mgba-emu/mgba/issues/996
and when I looked at the issue, I realized that it was always certain sounds overpowering other sounds (bass in one song, rhythm in another, always one instrument). I checked the tracker for other issues and found this one. I'm a pleb user and not knowledgeable about terminology but if the pulse channel was the problem here, then it's still the problem. This hasn't been fixed.

**Comment by arkazal** [comment]
I don't know what master is. I used 0.6.0 in Bizhawk, 0.6.1 downloaded from your site, and 0.6.1 in Bizhawk. All 3 versions have and still are giving me this sound. I'll gladly try something else though, just let me know what to download.

**Comment by bryc** [comment]
As far as I can tell the original issue here was fixed in https://github.com/libretro/mgba/commit/b3c4ab2cf66302b0ba4e97d2c5848ad436c277ad. Try RetroArch with the the latest mGBA core, "mGBA 0.6.1 b3c4ab2".

**Comment by arkazal** [comment]
I don't know what that alphanumeric means after mGBA 0.6.1. I'm taken to a page that lists a bunch of changes and has no files to download. I wish you guys wouldn't assume that everyone understands what goes on here in github land, some of us are completely new and don't know what "master", "b3c4ab2" and etc are :'(

**Comment by endrift** [comment]
My apologies, builds from master can be found here: https://mgba.io/downloads.html#development-downloads

**Comment by arkazal** [comment]
Ah, thanks. I had downloaded and tried 0.6.1 from that very page as part of my testing. I tried the hourly build as well now (hadn't noticed that before). After having given everything another listen:

- Stark Farm and the Kurukuru Kururin map still don't sound quite right, but the problem aren't the instruments I had said, so the pulse channel issue is probably fixed. Mostly, it just sounds a little muffled/muddy.
- Magical Houshin still sounds really off. However, I explored around with the audio options and actually narrowed the cause of this down to FIFO Channel A (disabling this channel eliminated the "instrument" in the music that is being produced with a tinny sound).
- The pulse channel issue is still present in Bizhawk, but I'm doubting that you're at fault for that (possibly this libretro thing I've seen mentioned?).

So mainly, the problem now is Magical Houshin, which isn't a pulse channel problem, but FIFO Channel A (whatever that correlates to). Many thanks for putting up with me thus far :'D

**Comment by endrift** [comment]
FIFO Channel A is DMA audio/direct sound. That's kind of disconcerting...
BizHawk currently uses mGBA 0.6.1 release, I believe. Progress has been made since then, but it hasn't gotten merged back in yet.

The pulse channels are 1 and 2.

**Comment by bryc** [comment]
@arkazal 

The "b3c4ab2" just refers to the commit id number. These pretty much identify development versions between stable versions.

Audio clips would definitely help. Get yourself Audacity and record the affected audio in mGBA and unaffected audio in other emulators (like gpSP, VBA-M, No$GBA, Meteor etc.). And try to give precise steps for reproducing/verifying the issue. The way you're currently describing it, "tinny", "muddy" is kinda vague. 

Hell, the GBA sound hardware itself was pretty bad since it didn't have a dedicated chip like the SNES. VBA-M has a bunch of filtering/interpolation/surround/stereo options that could make the sound much different than mGBA, are you sure it's not due to one of those options?
