### ISSUE TITLE
Rewind crashes mgba

### ISSUE THREAD

**Issue by themalu866** [mgba-emu/mgba#1311]
Playing on Windows. Doesn't always happens but when holding the rewind button the game crashes at the end of the Rewind History and this message appear.
But it only happens with rewind (held). Rewinding by pressing ~ doesn't even work, it freezes the emulator and then crashes. The game from the image is Super Mario Advance by the way.

![rew](https://user-images.githubusercontent.com/42208976/53064395-6f6ada80-34a6-11e9-934b-ff2fdd7923f7.png)

**Comment by endrift** [comment]
Having trouble reproducing, though I've fixed the hang.

**Comment by endrift** [comment]
Likely the same cause as #1235 and #1216.

**Comment by themalu866** [comment]
Yup, rewind causes a ton of glitches.
[Kid Icarus of Myths and Monsters.zip](https://github.com/mgba-emu/mgba/files/2948835/Kid.Icarus.of.Myths.and.Monsters.zip)

**Comment by endrift** [comment]
Please retest in latest dev.

**Comment by themalu866** [comment]
Yes, still happens.
![ttyt](https://user-images.githubusercontent.com/42208976/91017683-f41b4500-e5c4-11ea-9210-69274261efab.png)

**Comment by endrift** [comment]
Which game was this and what were your rewind settings?

**Comment by themalu866** [comment]
Super Mario Advance, settings are in the image.
![67657](https://user-images.githubusercontent.com/42208976/91019312-2d54b480-e5c7-11ea-9b86-71c477559b27.png)

**Comment by endrift** [comment]
Hm, seems like the problem with rewind might be something other than the savestates themselves then. Is your computer single core?

**Comment by themalu866** [comment]
I think it isn't.

**Comment by endrift** [comment]
This might be fixed in the commit I just pushed. I'm still having trouble reproducing though so I can't confirm.

**Comment by TheYadda** [comment]
Just for documentation's sake, having similar issue with Metroid: Zero Mission on 0.9.1, after resuming from a save state. Issue did not present before resuming from save state, despite heavy use of rewind function. Settings are default on a 100% fresh install aside from rewind 1000 frames and controller bindings. Willing to help test if needed.
