### ISSUE TITLE
OpenGL/Zelda Minish Cap: Temporal glitches when resetting the game in the middle of a conversation

### ISSUE THREAD

**Issue by RafaelTrepaUnCarballo** [mgba-emu/mgba#1706]
With OpenGL High resolution mode, if you reset the game (Ctrl+R) during a conversation some sprite leftovers remains during the boot.

![Legend of Zelda, The - The Minish Cap (Europe) (En,Fr,De,Es,It) European Backport Edition Patch-0](https://user-images.githubusercontent.com/16591467/77836733-0352af80-7159-11ea-9254-6a25ec2da33e.png)

I tested the European version of the game and the latest build.

**Comment by endrift** [comment]
Latest build? This should have been fixed a while ago...

**Comment by RafaelTrepaUnCarballo** [comment]
Yes, latest win64 build

**Comment by angelxd84130** [comment]
Hey,
I tried the last release 0.9-6160 on both Win10 and macOS and run games of European and USA version,  they work fine. I think they have solved the problem :)
![legend-of-zelda-the-the-minish-cap-usa-1](https://user-images.githubusercontent.com/19487525/79058235-20d74d00-7c20-11ea-820f-a686036ebeca.png)

**Comment by RafaelTrepaUnCarballo** [comment]
No, they haven't. It still happens with the OpenGL HD render

**Comment by endrift** [comment]
I'm unable to reproduce this. What is your GPU?

**Comment by RafaelTrepaUnCarballo** [comment]
Nvidia 820M/Intel HD4600... but it doesn't matter anymore.

The bug were fixed between 0.9-6156-8d194fa9 and the latest 0.9-6191-3ef59bd2c.
Thanks for you work, endrift.
