### ISSUE TITLE
Choppy fastforward framerate in 0.9.2 and later

### ISSUE THREAD

**Issue by Dullstar** [mgba-emu/mgba#2549]
64-bit versions were used on Windows 10 64 bit. Didn't test 32-bit builds.
Initially noticed issue in 0.9.3
Latest unaffected version that I tested: 0.9.1
Earliest affected version that I tested: 0.9.2
Latest version I tested: 0.10-7531-b43509e70 (it's still affected)

I like to run certain games at higher speeds. In earlier versions, this works fine (using 2.50x speed for a balance between speed and control). Of course, certainly not every frame is getting rendered, because this is running at a higher framerate than my monitor can draw, but it still looks smooth enough. On 0.9.2 and later, it appears to be dropping more frames than is necessitated by the difference in the game speed vs. the monitor refresh rate. The game still runs at the expected speed, but the draw speed appears to have dipped far below the monitor refresh rate of 60 Hz. It does not appear to be game-specific, but may be more noticeable on certain games (more motion = more noticeable).

I don't have an easy way to actually measure it, but I'd estimate the framerate that's actually being displayed in fast forward to be somewhere around 20 to 30.

It seems fine when running at normal speed. Frameskip is not enabled. There is no evidence of the CPU (intel i5-6600, 3.30GHz, 4 cores as reported by Windows) being even close to maxed out (neither overall nor any individual core), nor is there evidence of the GPU (3060 Ti) being maxed out. When testing in different versions I used portable installations to avoid issues with pre-existing configurations and only changed the fast-forward speed from unbounded to 2.50.

I have not tested the unbounded settings, because at the unbounded speed the games aren't really playable and so many frames have to be skipped just because of the refresh rate that it's harder to tell what's going on at all.

Current workaround: Use 0.9.1 or put up with it. It's enough to bother me, so I'll use 0.9.1 for now.

**Comment by endrift** [comment]
This should have been fixed in 0.10.0 and I guess I forgot to ask if it works now

**Comment by Dullstar** [comment]
I'm still noticing it but I should probably try to get some better measurements to see what's actually different (visually speaking) between the latest version and 0.9.1. It's definitely not possible to draw all the frames, of course, because the refresh rate of the monitor is too low, but it *seems* like 0.9.1 hides it better somehow; I'll try to investigate further and see if I can figure out exactly what's different that makes it less apparent to me in 0.9.1; it's probably going to require doing some screen recording and then going frame-by-frame.

**Comment by Obnoxygen** [comment]
I'm also having the same issue. When I compared it with VBA-M, I've noticed that the fast-forward setting in that emulator has an option to enable/disable frame-skipping (aside from the general frame-skipping setting). So, it appears to me that in mGBA, the fast-forward setting automatically enables frame-skipping and there is no option to disable it. If that is really the case, I hope this would be fixed soon because the fast-forward is very very choppy.

**Comment by Dullstar** [comment]
I retested today, and confirmed this still occurs in 0.10.4.

Using Obnoxygen's observations regarding frameskip both here and in [this report](https://github.com/mgba-emu/mgba/issues/3387), I messed around a bit with OBS and made the observation that if I set it to capture 0.9.1 at 30 fps, the recording shows comparable visual choppiness to what I observe in 0.10.4. At 60 fps this doesn't happen. When viewing back the 0.10.4 60 fps footage frame-by-frame, I can confirm that mGBA appears to be rendering at 30fps, as I have to click the next frame button *twice* to see the next frame that mGBA draws.

Fast forward speed for this test was set to 4.00x.

Interestingly the 0.9.1x footage appears possibly inconsistent as to how many frames are skipped rendering at 60fps, though since it's not drawing the same frame twice it's far less noticeable.

https://github.com/user-attachments/assets/85444126-9aa7-4059-9d9e-88e0e3b03183

https://github.com/user-attachments/assets/e789587c-2e3d-4507-a1ee-a6122e1894d5

https://github.com/user-attachments/assets/d9305f75-afb8-4420-9290-5b0065f9ba6e
