### ISSUE TITLE
Frame size option broken

### ISSUE THREAD

**Issue by LunarLambda** [mgba-emu/mgba#2973]
Every frame size option sets the window size to 1x, and multiple boxes can be checked at the same time, and then not unchecked. When restarting mGBA afterwards the window is either 1x again or maximized.

(screen photo because screenshotting X11 menus is a nightmare)
![image](https://github.com/mgba-emu/mgba/assets/38919842/6c1e1007-7962-459e-9ad1-dc0021f63e57)

[bug.zip](https://github.com/mgba-emu/mgba/files/11955489/bug.zip)

**Comment by RetroEdit** [comment]
This is not broken in 0.10.2, but it is broken in a recent dev version (6a31777).

Specifically, it only happens when you try and change the setting when a game isn't loaded. If a game is loaded, it appears to work properly.

**Comment by RetroEdit** [comment]
I did a bisect from dev downloads, but unfortunately a few dozen builds were missing in the relevant time period, presumably because of merging in 'feature/canvas': [9a4cf28](https://github.com/mgba-emu/mgba/commit/9a4cf2877642fe32dda692270547cd81e4705654) had the bug, [eb7b90e](https://github.com/mgba-emu/mgba/commit/eb7b90e5d9d226fdba025e9594ccfc82f6e43ad4) didn't have it.

**Comment by endrift** [comment]
That actually tells me enough to know it was caused by the introduction of the Display::contentSize() method, or surrounding code changes.

**Comment by Nximus** [comment]
Has there been a solution found for this? I have the same problem and it happened on 0.10.2 AND 0.10.3

**Comment by endrift** [comment]
I believe this was fixed in e8e6b803f25d0a873bcce75d71c4ff40ef4371ae, please confirm.

**Comment by Nximus** [comment]
It seems to still be giving me issues. The resizing works fine with no game and with GB/GBC games running. When launching a GBA game though it returns to the usual bug. 

(Tested GB with Pokemon Red, GBC with Pokemon Crystal and GBA with Pokemon Emerald and Fire Red)

![image](https://github.com/mgba-emu/mgba/assets/21041859/f4c6a62f-952c-416b-a3a7-5739514a28a4)

**Comment by LunarLambda** [comment]
Compiled version `0.11-8402-d1a6e6b74` and it seems to work fine for me (on Arch Linux). Did also verify that the version used in the original post was broken on this machine too since it was on a different machine previously.

**Comment by Nximus** [comment]
I tried the same version as LunarLambda above on Windows and GBA titles are still broken. After using the "shutdown" button with a gba game running the menu screen has the same resizing issue.
![image](https://github.com/mgba-emu/mgba/assets/21041859/bde5200e-e5a9-4c1e-9860-da668da2bbf5)

**Comment by 72374** [comment]
With the current development-version (9122), the issue with the multiple selectable checkboxes happens, when the currently chosen option results in a resolution that does not fit on the screen. Choosing another "Frame size"-option, for another resolution that is too high, will select another checkbox, until one for a fitting resolution is chosen, which does then correct the chosen options. Increasing "High-resolution scale", makes this happen for more of the options, after a game was started.

I guess that the target-resolution for each "Frame size"-option is also supposed to be a multiple of the original resolution of a GBA, instead of the increased resolution.

**Comment by endrift** [comment]
I made a bunch of changes to this in aa6394c93ca24b0ff40dc9231bdb0533f415e0be. Can you retest on 9133-aa6394c93 or newer?

**Comment by 72374** [comment]
The issue with multiple selections seems to be solved in development-version 9133 (x64, AppImage; also with a local build).

While "Lock Screen Size" is enabled, the chosen size-limit is also applied after restarting; which did not happen in the versions that i did use before.
Though the size and the value of the selected option are either multiplied or divided by the value of the "High-resolution scale"-setting when starting a game (multiplied on first game-start per session, divided after that).
Deleting those 3 lines seems to solve this:
https://github.com/mgba-emu/mgba/blob/aa6394c93ca24b0ff40dc9231bdb0533f415e0be/src/platform/qt/Window.cpp#L916-L918

---

Some other issues related to the options in the "Frame size"-menu:

1. After closing mGBA in non-maximised window-mode, with "Lock Screen Size" enabled, the window-size will change to 258x256 (measured from a screen-image) when starting mGBA again.
2. When choosing a frame-size, with "Lock Screen Size" enabled, before starting any game, the size of games will not be limited to a chosen size-option. After restarting mGBA, the size-option that was last set after starting a game will be used again.
3. When choosing a frame-size in fullscreen-mode, with "Lock Screen Size" disabled, it will exit fullscreen-mode, keeping the previous window-size; mGBA 0.10.5 does resize the window to the chosen frame-size then.

**Comment by endrift** [comment]
Behavior should be improved now. I don't think any of the numbered points are fixed yet, but locked screen size with a scaling number should be fixed when loading a game. I'm going to continue looking into the others soon.
