### ISSUE TITLE
SGB border visual glitch

### ISSUE THREAD

**Issue by chiascuro** [mgba-emu/mgba#3191]
This was tested on mgba version 10.2, 10.3 and the latest development build (2024-04-17)
Game: Pokémon Crystal Clear (Romhack) link: https://shockslayer.com/crystal-clear/ (I included the patch files in the zip)
Patched here (official site) with SGB mode enabled https://inject.sigkill.tech/patch/cc
Tried both, Version 1.0 and 1.1 of Pokémon Crystal as the base

[Video of the issue/how to replicate it](https://pantsu.review/6bZa7tq.mp4)
Basically, opening the Pokédex and closing it messes up the whole screen. Using the Pokédex, one can change the border color of the SGB Border (Cyan in the video), so it's probably just trying to update that. As seen in the video it can be fixed by switching party members as that also interacts with the SGB border.

This issue does not appear with the BGB emulator.

All other necessary information should be included in the automatically generated bug report zip file
[bug report.zip](https://github.com/mgba-emu/mgba/files/15020744/bug.zip)

**Comment by endrift** [comment]
I thought I fixed this one already...it keeps coming back.

**Comment by endrift** [comment]
I remember now. This is actually a bug in Crystal Clear. I'm pretty sure it was fixed at some point. I backed out the patch that fixed it (8a87eaa395ca4e84f8841ad8a2cd684d8a9f6c06) because it was clearly erroneous to include. It's not real hardware so there's no "well defined" way to do this, but it was special casing for one ROM hack so I didn't want to keep it. I guess bgb decided to leave that special casing in.

Please use an up-to-date version of Crystal Clear to confirm.

**Comment by chiascuro** [comment]
I tried it with the latest patch (2.5.10), I didn't find the files for 2.5.9 so I couldn't try it with the older one. I tried both, the normal version and the color filter version. I tried it on my current mgba installation and on the latest development build. The bug still persists

**Comment by endrift** [comment]
Hmm, alright, I'll take a closer look.

**Comment by endrift** [comment]
Reverting the reversion fixes it. Ugh. Looks like Crystal Clear still has the bug. I need to figure out if I work around their bug or pressure them to fix it instead.

**Comment by ShockSlayer** [comment]
No need for any pressure. I agree that mGBA should not have any special handling just for one hack. I thought I had fixed this on my end as of CC 2.5.3 by disabling OBJs when updating the border, but I've just checked both that version and the latest against mGBA 0.10.3 and I'm able to replicate this. I guess either I didn't properly fix this, or if I did, it was only partially, since updating the border seems to work correctly in most other places.

I've made a note of this, and I'll see if I can work it out before the next version. I apologize for any confusion and appreciate your insight into figuring this out.

**Comment by endrift** [comment]
Ah so I wasn't crazy! I didn't realize you had a GitHub account or I would have tagged you. I was discussing this with beware on the gbdev Discord and he said that the SGBC implementation in bgb is kind of ad hoc and not necessarily known to be well behaved, so we agreed to clean it up to make it more consistent. Hopefully it'll lead to it being caught before release if it regresses again.

**Comment by endrift** [comment]
@ShockSlayer While looking into this last night, beware noticed that you don't set BGP to $e4. Since this is a GBC-only game and that's a GB-only register that makes sense, but the SGB requires that for VRAM transfers to work properly. I don't think we're going to enforce that in SGBC, but it would be appreciated if you set it once on startup just for good measure, as that's what licensed titles that happen to upload borders in GBC mode do.

**Comment by ShockSlayer** [comment]
Cool. I'll make a note of that as well.

**Comment by ShockSlayer** [comment]
I've dropped 2.5.11 today which should fix this; at least, it appears to work correctly on both mGBA and BGB. All I did was adjust a delay back to the original value; BGP was already being set to $e4 in the correct places.

Hopefully this puts the issue to bed. Sorry for taking so long; busy year.
